apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wave-app
  namespace: argocd
spec:
  description: Wave-App GitOps project
  sourceRepos:
    - https://github.com/dordor22/wave-gitops
    - https://github.com/dordor22/wave-app
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
